# Generated by Django 4.2.23 on 2025-06-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_run_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='time',
            field=models.DurationField(help_text='Time duration (hh:mm)'),
        ),
    ]
